# Project 2 - Evaluating Billboard Data Set

### Problem Statement

The billboard dataset that is provided is the Billboard top 100 songs in the year 2000. The dataset must be cleaned to ensure proper fields are in integer data types to conduct statistical analysis. Also Genre field must be cleaned up to show proper genre for a given artist. This will be done in the csv itself.

### Assumptions

Assumption 1: one genre per artist. The data set genre fields must be cleaned up, as there are two variations of rock (rock and rock n roll) and two variations of R&B (R&B and R & B).

Assumption 2: the time is the track length, which will be converted in total seconds

In [665]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
%matplotlib inline

In [666]:
pwd ='/Users/amishdalal/DSI-NYC-2/curriculum/week-02/2.3-data-cleaning/assets/datasets/billboard.csv'

In [667]:
f = pd.read_csv(pwd)

In [668]:
bb = pd.DataFrame(f)
orig_bb = bb.copy()
bb.head()

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",Rock,"September 23, 2000","November 18, 2000",78,63,49,...,*,*,*,*,*,*,*,*,*,*
1,2000,Santana,"Maria, Maria","4,18,00 AM",Rock,"February 12, 2000","April 8, 2000",15,8,6,...,*,*,*,*,*,*,*,*,*,*
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",Rock,"October 23, 1999","January 29, 2000",71,48,43,...,*,*,*,*,*,*,*,*,*,*
3,2000,Madonna,Music,"3,45,00 AM",Rock,"August 12, 2000","September 16, 2000",41,23,18,...,*,*,*,*,*,*,*,*,*,*
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",Rock,"August 5, 2000","October 14, 2000",57,47,45,...,*,*,*,*,*,*,*,*,*,*

### Printing all the data types below to check each column's data type

Time will be converted into int64 (will create a new column), and date.entered, date.peaked will be converted to datetime objects

In [669]:
bb.dtypes

year                int64
artist.inverted    object
track              object
time               object
genre              object
date.entered       object
date.peaked        object
x1st.week           int64
x2nd.week          object
x3rd.week          object
x4th.week          object
x5th.week          object
x6th.week          object
x7th.week          object
x8th.week          object
x9th.week          object
x10th.week         object
x11th.week         object
x12th.week         object
x13th.week         object
x14th.week         object
x15th.week         object
x16th.week         object
x17th.week         object
x18th.week         object
x19th.week         object
x20th.week         object
x21st.week         object
x22nd.week         object
x23rd.week         object
                    ...
x47th.week         object
x48th.week         object
x49th.week         object
x50th.week         object
x51st.week         object
x52nd.week         object
x53rd.week         object
x54th.week         object
x55th.week         object
x56th.week         object
x57th.week         object
x58th.week         object
x59th.week         object
x60th.week         object
x61st.week         object
x62nd.week         object
x63rd.week         object
x64th.week         object
x65th.week         object
x66th.week         object
x67th.week         object
x68th.week         object
x69th.week         object
x70th.week         object
x71st.week         object
x72nd.week         object
x73rd.week         object
x74th.week         object
x75th.week         object
x76th.week         object
dtype: object

### Let's rename the artist.inverted column to artist and replace all "." to "_" in the column titles

In [670]:
bb = bb.rename(columns = {'artist.inverted':'artist'})
bb.columns = bb.columns.str.replace('.','_')
print len(bb)
bb.head()

317

,year,artist,track,time,genre,date_entered,date_peaked,x1st_week,x2nd_week,x3rd_week,...,x67th_week,x68th_week,x69th_week,x70th_week,x71st_week,x72nd_week,x73rd_week,x74th_week,x75th_week,x76th_week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",Rock,"September 23, 2000","November 18, 2000",78,63,49,...,*,*,*,*,*,*,*,*,*,*
1,2000,Santana,"Maria, Maria","4,18,00 AM",Rock,"February 12, 2000","April 8, 2000",15,8,6,...,*,*,*,*,*,*,*,*,*,*
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",Rock,"October 23, 1999","January 29, 2000",71,48,43,...,*,*,*,*,*,*,*,*,*,*
3,2000,Madonna,Music,"3,45,00 AM",Rock,"August 12, 2000","September 16, 2000",41,23,18,...,*,*,*,*,*,*,*,*,*,*
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",Rock,"August 5, 2000","October 14, 2000",57,47,45,...,*,*,*,*,*,*,*,*,*,*

### Convert date_entered and date_peaked columns from object to datetime objects

In [671]:
bb['date_entered'] = pd.to_datetime(bb['date_entered'])
bb['date_peaked'] = pd.to_datetime(bb['date_peaked'])

### Converting time column to creating a track length column

In [672]:
l = []
for x in bb['time']:
    l.append(x.split(','))

print l

[['3', '38', '00 AM'], ['4', '18', '00 AM'], ['4', '07', '00 AM'], ['3', '45', '00 AM'], ['3', '38', '00 AM'], ['4', '17', '00 AM'], ['4', '31', '00 AM'], ['3', '36', '00 AM'], ['3', '52', '00 AM'], ['4', '25', '00 AM'], ['3', '10', '00 AM'], ['3', '18', '00 AM'], ['4', '01', '00 AM'], ['3', '52', '00 AM'], ['4', '03', '00 AM'], ['4', '12', '00 AM'], ['4', '14', '00 AM'], ['4', '04', '00 AM'], ['3', '50', '00 AM'], ['3', '43', '00 AM'], ['4', '21', '00 AM'], ['3', '50', '00 AM'], ['3', '24', '00 AM'], ['3', '48', '00 AM'], ['3', '53', '00 AM'], ['4', '05', '00 AM'], ['4', '00', '00 AM'], ['4', '16', '00 AM'], ['4', '57', '00 AM'], ['4', '34', '00 AM'], ['3', '15', '00 AM'], ['4', '42', '00 AM'], ['4', '06', '00 AM'], ['3', '19', '00 AM'], ['3', '46', '00 AM'], ['3', '51', '00 AM'], ['3', '52', '00 AM'], ['4', '23', '00 AM'], ['3', '56', '00 AM'], ['3', '54', '00 AM'], ['3', '09', '00 AM'], ['4', '03', '00 AM'], ['2', '52', '00 AM'], ['3', '29', '00 AM'], ['5', '03', '00 AM'], ['3', '23', '00 AM'], ['5', '16', '00 AM'], ['4', '17', '00 AM'], ['4', '03', '00 AM'], ['7', '50', '00 AM'], ['3', '48', '00 AM'], ['3', '30', '00 AM'], ['3', '49', '00 AM'], ['4', '30', '00 AM'], ['4', '05', '00 AM'], ['3', '42', '00 AM'], ['3', '04', '00 AM'], ['3', '50', '00 AM'], ['4', '23', '00 AM'], ['4', '23', '00 AM'], ['4', '02', '00 AM'], ['4', '46', '00 AM'], ['3', '35', '00 AM'], ['4', '30', '00 AM'], ['3', '57', '00 AM'], ['4', '13', '00 AM'], ['3', '57', '00 AM'], ['3', '46', '00 AM'], ['3', '30', '00 AM'], ['3', '35', '00 AM'], ['3', '52', '00 AM'], ['3', '55', '00 AM'], ['5', '27', '00 AM'], ['3', '55', '00 AM'], ['4', '19', '00 AM'], ['4', '08', '00 AM'], ['3', '22', '00 AM'], ['4', '07', '00 AM'], ['3', '55', '00 AM'], ['3', '50', '00 AM'], ['4', '14', '00 AM'], ['3', '32', '00 AM'], ['4', '16', '00 AM'], ['3', '43', '00 AM'], ['3', '41', '00 AM'], ['3', '25', '00 AM'], ['3', '22', '00 AM'], ['3', '08', '00 AM'], ['3', '45', '00 AM'], ['4', '13', '00 AM'], ['3', '03', '00 AM'], ['3', '37', '00 AM'], ['2', '38', '00 AM'], ['3', '23', '00 AM'], ['4', '41', '00 AM'], ['3', '50', '00 AM'], ['4', '09', '00 AM'], ['3', '54', '00 AM'], ['4', '12', '00 AM'], ['3', '42', '00 AM'], ['7', '10', '00 AM'], ['3', '17', '00 AM'], ['4', '28', '00 AM'], ['3', '30', '00 AM'], ['3', '57', '00 AM'], ['3', '45', '00 AM'], ['4', '51', '00 AM'], ['3', '37', '00 AM'], ['4', '15', '00 AM'], ['6', '50', '00 AM'], ['3', '47', '00 AM'], ['4', '18', '00 AM'], ['4', '07', '00 AM'], ['3', '12', '00 AM'], ['5', '19', '00 AM'], ['4', '33', '00 AM'], ['4', '15', '00 AM'], ['4', '30', '00 AM'], ['6', '22', '00 AM'], ['3', '45', '00 AM'], ['3', '30', '00 AM'], ['3', '46', '00 AM'], ['3', '29', '00 AM'], ['3', '24', '00 AM'], ['3', '32', '00 AM'], ['4', '02', '00 AM'], ['3', '26', '00 AM'], ['4', '10', '00 AM'], ['7', '35', '00 AM'], ['3', '43', '00 AM'], ['3', '44', '00 AM'], ['5', '36', '00 AM'], ['3', '54', '00 AM'], ['4', '34', '00 AM'], ['3', '51', '00 AM'], ['4', '15', '00 AM'], ['3', '52', '00 AM'], ['3', '23', '00 AM'], ['3', '54', '00 AM'], ['4', '20', '00 AM'], ['4', '00', '00 AM'], ['3', '45', '00 AM'], ['2', '53', '00 AM'], ['3', '19', '00 AM'], ['4', '11', '00 AM'], ['4', '00', '00 AM'], ['3', '36', '00 AM'], ['4', '23', '00 AM'], ['4', '07', '00 AM'], ['3', '33', '00 AM'], ['3', '46', '00 AM'], ['2', '55', '00 AM'], ['3', '48', '00 AM'], ['3', '52', '00 AM'], ['3', '17', '00 AM'], ['5', '03', '00 AM'], ['5', '13', '00 AM'], ['4', '38', '00 AM'], ['2', '53', '00 AM'], ['3', '40', '00 AM'], ['3', '40', '00 AM'], ['4', '04', '00 AM'], ['3', '04', '00 AM'], ['5', '28', '00 AM'], ['3', '55', '00 AM'], ['4', '07', '00 AM'], ['2', '36', '00 AM'], ['3', '30', '00 AM'], ['4', '27', '00 AM'], ['3', '48', '00 AM'], ['4', '31', '00 AM'], ['4', '12', '00 AM'], ['3', '56', '00 AM'], ['4', '05', '00 AM'], ['4', '41', '00 AM'], ['5', '20', '00 AM'], ['4', '12', '00 AM'], ['3', '16', '00 AM'], ['5', '26', '00 AM'], ['4', '23', '00 AM'], ['4', '28', '00 AM'], ['4', '10', '00 AM'], ['4', '36', '00 AM'], ['4', '13', '00 AM'], ['3', '54', '00 AM'], ['4', '20', '00 AM'], ['3', '56', '00 AM'], ['3', '50', '00 AM'], ['3', '39', '00 AM'], ['4', '17', '00 AM'], ['4', '11', '00 AM'], ['4', '09', '00 AM'], ['3', '41', '00 AM'], ['4', '24', '00 AM'], ['2', '58', '00 AM'], ['4', '05', '00 AM'], ['4', '42', '00 AM'], ['3', '44', '00 AM'], ['3', '20', '00 AM'], ['3', '19', '00 AM'], ['5', '30', '00 AM'], ['4', '22', '00 AM'], ['4', '10', '00 AM'], ['2', '55', '00 AM'], ['3', '56', '00 AM'], ['4', '08', '00 AM'], ['4', '40', '00 AM'], ['3', '51', '00 AM'], ['4', '02', '00 AM'], ['5', '33', '00 AM'], ['3', '26', '00 AM'], ['3', '36', '00 AM'], ['4', '12', '00 AM'], ['5', '00', '00 AM'], ['3', '46', '00 AM'], ['3', '55', '00 AM'], ['3', '51', '00 AM'], ['3', '19', '00 AM'], ['3', '50', '00 AM'], ['4', '12', '00 AM'], ['5', '26', '00 AM'], ['3', '12', '00 AM'], ['4', '00', '00 AM'], ['3', '51', '00 AM'], ['4', '04', '00 AM'], ['4', '16', '00 AM'], ['3', '47', '00 AM'], ['3', '05', '00 AM'], ['5', '12', '00 AM'], ['6', '20', '00 AM'], ['3', '50', '00 AM'], ['4', '02', '00 AM'], ['4', '18', '00 AM'], ['5', '00', '00 AM'], ['5', '21', '00 AM'], ['4', '10', '00 AM'], ['2', '56', '00 AM'], ['3', '42', '00 AM'], ['3', '59', '00 AM'], ['4', '45', '00 AM'], ['4', '35', '00 AM'], ['4', '17', '00 AM'], ['3', '27', '00 AM'], ['4', '06', '00 AM'], ['3', '33', '00 AM'], ['4', '13', '00 AM'], ['4', '22', '00 AM'], ['3', '29', '00 AM'], ['3', '37', '00 AM'], ['3', '55', '00 AM'], ['3', '56', '00 AM'], ['4', '19', '00 AM'], ['4', '06', '00 AM'], ['5', '43', '00 AM'], ['3', '10', '00 AM'], ['3', '23', '00 AM'], ['3', '25', '00 AM'], ['3', '35', '00 AM'], ['3', '50', '00 AM'], ['3', '07', '00 AM'], ['3', '54', '00 AM'], ['3', '02', '00 AM'], ['4', '30', '00 AM'], ['4', '26', '00 AM'], ['3', '40', '00 AM'], ['4', '00', '00 AM'], ['4', '06', '00 AM'], ['4', '32', '00 AM'], ['4', '18', '00 AM'], ['4', '06', '00 AM'], ['4', '04', '00 AM'], ['3', '25', '00 AM'], ['4', '16', '00 AM'], ['4', '18', '00 AM'], ['3', '45', '00 AM'], ['2', '56', '00 AM'], ['4', '57', '00 AM'], ['3', '55', '00 AM'], ['4', '17', '00 AM'], ['3', '40', '00 AM'], ['4', '38', '00 AM'], ['3', '51', '00 AM'], ['6', '17', '00 AM'], ['3', '38', '00 AM'], ['3', '27', '00 AM'], ['3', '19', '00 AM'], ['3', '43', '00 AM'], ['3', '15', '00 AM'], ['3', '44', '00 AM'], ['3', '48', '00 AM'], ['4', '08', '00 AM'], ['4', '11', '00 AM'], ['3', '54', '00 AM'], ['4', '02', '00 AM'], ['4', '10', '00 AM'], ['3', '47', '00 AM'], ['3', '23', '00 AM'], ['4', '14', '00 AM'], ['3', '46', '00 AM'], ['5', '10', '00 AM'], ['4', '43', '00 AM'], ['4', '01', '00 AM'], ['2', '58', '00 AM'], ['4', '17', '00 AM'], ['3', '44', '00 AM'], ['4', '16', '00 AM'], ['5', '02', '00 AM'], ['4', '02', '00 AM'], ['4', '24', '00 AM'], ['4', '06', '00 AM'], ['4', '00', '00 AM'], ['3', '33', '00 AM'], ['3', '04', '00 AM'], ['3', '58', '00 AM'], ['3', '30', '00 AM'], ['3', '58', '00 AM'], ['3', '22', '00 AM']]

In [673]:
sec = []
for x in l:
    minutes = int(x[0])
    seconds = int(x[1])
    total = minutes * 60 + seconds
    sec.append(total)
print sec
len(sec)

[218, 258, 247, 225, 218, 257, 271, 216, 232, 265, 190, 198, 241, 232, 243, 252, 254, 244, 230, 223, 261, 230, 204, 228, 233, 245, 240, 256, 297, 274, 195, 282, 246, 199, 226, 231, 232, 263, 236, 234, 189, 243, 172, 209, 303, 203, 316, 257, 243, 470, 228, 210, 229, 270, 245, 222, 184, 230, 263, 263, 242, 286, 215, 270, 237, 253, 237, 226, 210, 215, 232, 235, 327, 235, 259, 248, 202, 247, 235, 230, 254, 212, 256, 223, 221, 205, 202, 188, 225, 253, 183, 217, 158, 203, 281, 230, 249, 234, 252, 222, 430, 197, 268, 210, 237, 225, 291, 217, 255, 410, 227, 258, 247, 192, 319, 273, 255, 270, 382, 225, 210, 226, 209, 204, 212, 242, 206, 250, 455, 223, 224, 336, 234, 274, 231, 255, 232, 203, 234, 260, 240, 225, 173, 199, 251, 240, 216, 263, 247, 213, 226, 175, 228, 232, 197, 303, 313, 278, 173, 220, 220, 244, 184, 328, 235, 247, 156, 210, 267, 228, 271, 252, 236, 245, 281, 320, 252, 196, 326, 263, 268, 250, 276, 253, 234, 260, 236, 230, 219, 257, 251, 249, 221, 264, 178, 245, 282, 224, 200, 199, 330, 262, 250, 175, 236, 248, 280, 231, 242, 333, 206, 216, 252, 300, 226, 235, 231, 199, 230, 252, 326, 192, 240, 231, 244, 256, 227, 185, 312, 380, 230, 242, 258, 300, 321, 250, 176, 222, 239, 285, 275, 257, 207, 246, 213, 253, 262, 209, 217, 235, 236, 259, 246, 343, 190, 203, 205, 215, 230, 187, 234, 182, 270, 266, 220, 240, 246, 272, 258, 246, 244, 205, 256, 258, 225, 176, 297, 235, 257, 220, 278, 231, 377, 218, 207, 199, 223, 195, 224, 228, 248, 251, 234, 242, 250, 227, 203, 254, 226, 310, 283, 241, 178, 257, 224, 256, 302, 242, 264, 246, 240, 213, 184, 238, 210, 238, 202]

317

In [674]:
type(sec)
total_sec = pd.Series(sec)

In [675]:
bb.insert(4,'Total_Sec',total_sec)

In [676]:
bb.dtypes

year                     int64
artist                  object
track                   object
time                    object
Total_Sec                int64
genre                   object
date_entered    datetime64[ns]
date_peaked     datetime64[ns]
x1st_week                int64
x2nd_week               object
x3rd_week               object
x4th_week               object
x5th_week               object
x6th_week               object
x7th_week               object
x8th_week               object
x9th_week               object
x10th_week              object
x11th_week              object
x12th_week              object
x13th_week              object
x14th_week              object
x15th_week              object
x16th_week              object
x17th_week              object
x18th_week              object
x19th_week              object
x20th_week              object
x21st_week              object
x22nd_week              object
                     ...
x47th_week              object
x48th_week              object
x49th_week              object
x50th_week              object
x51st_week              object
x52nd_week              object
x53rd_week              object
x54th_week              object
x55th_week              object
x56th_week              object
x57th_week              object
x58th_week              object
x59th_week              object
x60th_week              object
x61st_week              object
x62nd_week              object
x63rd_week              object
x64th_week              object
x65th_week              object
x66th_week              object
x67th_week              object
x68th_week              object
x69th_week              object
x70th_week              object
x71st_week              object
x72nd_week              object
x73rd_week              object
x74th_week              object
x75th_week              object
x76th_week              object
dtype: object

In [677]:
bb.head()

,year,artist,track,time,Total_Sec,genre,date_entered,date_peaked,x1st_week,x2nd_week,...,x67th_week,x68th_week,x69th_week,x70th_week,x71st_week,x72nd_week,x73rd_week,x74th_week,x75th_week,x76th_week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",218,Rock,2000-09-23,2000-11-18,78,63,...,*,*,*,*,*,*,*,*,*,*
1,2000,Santana,"Maria, Maria","4,18,00 AM",258,Rock,2000-02-12,2000-04-08,15,8,...,*,*,*,*,*,*,*,*,*,*
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",247,Rock,1999-10-23,2000-01-29,71,48,...,*,*,*,*,*,*,*,*,*,*
3,2000,Madonna,Music,"3,45,00 AM",225,Rock,2000-08-12,2000-09-16,41,23,...,*,*,*,*,*,*,*,*,*,*
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",218,Rock,2000-08-05,2000-10-14,57,47,...,*,*,*,*,*,*,*,*,*,*

In [678]:
def replace_nulls(value):
    if value == '*':
        return np.nan
    else:
        return value

In [679]:
bb = bb.applymap(replace_nulls)
bb.head()

,year,artist,track,time,Total_Sec,genre,date_entered,date_peaked,x1st_week,x2nd_week,...,x67th_week,x68th_week,x69th_week,x70th_week,x71st_week,x72nd_week,x73rd_week,x74th_week,x75th_week,x76th_week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",218,Rock,2000-09-23,2000-11-18,78,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria","4,18,00 AM",258,Rock,2000-02-12,2000-04-08,15,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",247,Rock,1999-10-23,2000-01-29,71,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,"3,45,00 AM",225,Rock,2000-08-12,2000-09-16,41,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",218,Rock,2000-08-05,2000-10-14,57,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [680]:
bb.loc[:,[x for x in bb.columns if 'week' in x]].isnull().sum()

x1st_week       0
x2nd_week       5
x3rd_week      10
x4th_week      17
x5th_week      25
x6th_week      37
x7th_week      48
x8th_week      57
x9th_week      64
x10th_week     73
x11th_week     81
x12th_week     95
x13th_week    107
x14th_week    113
x15th_week    120
x16th_week    135
x17th_week    140
x18th_week    151
x19th_week    161
x20th_week    171
x21st_week    252
x22nd_week    262
x23rd_week    269
x24th_week    271
x25th_week    279
x26th_week    281
x27th_week    288
x28th_week    293
x29th_week    297
x30th_week    297
             ...
x47th_week    312
x48th_week    313
x49th_week    313
x50th_week    313
x51st_week    313
x52nd_week    313
x53rd_week    313
x54th_week    315
x55th_week    315
x56th_week    315
x57th_week    315
x58th_week    315
x59th_week    315
x60th_week    315
x61st_week    315
x62nd_week    315
x63rd_week    315
x64th_week    315
x65th_week    316
x66th_week    317
x67th_week    317
x68th_week    317
x69th_week    317
x70th_week    317
x71st_week    317
x72nd_week    317
x73rd_week    317
x74th_week    317
x75th_week    317
x76th_week    317
dtype: int64

In [681]:
bb = bb.dropna(how = 'all', axis = 1)
bb.head()

,year,artist,track,time,Total_Sec,genre,date_entered,date_peaked,x1st_week,x2nd_week,...,x56th_week,x57th_week,x58th_week,x59th_week,x60th_week,x61st_week,x62nd_week,x63rd_week,x64th_week,x65th_week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",218,Rock,2000-09-23,2000-11-18,78,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria","4,18,00 AM",258,Rock,2000-02-12,2000-04-08,15,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",247,Rock,1999-10-23,2000-01-29,71,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,"3,45,00 AM",225,Rock,2000-08-12,2000-09-16,41,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",218,Rock,2000-08-05,2000-10-14,57,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [682]:
bb[bb.loc[:,[x for x in bb.columns if 'week' in x]].columns]

,x1st_week,x2nd_week,x3rd_week,x4th_week,x5th_week,x6th_week,x7th_week,x8th_week,x9th_week,x10th_week,...,x56th_week,x57th_week,x58th_week,x59th_week,x60th_week,x61st_week,x62nd_week,x63rd_week,x64th_week,x65th_week
0,78,63,49,33,23,15,7,5,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15,8,6,5,2,3,2,2,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,71,48,43,31,20,13,7,6,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41,23,18,14,2,1,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,57,47,45,29,23,18,11,9,9,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,59,52,43,30,29,22,15,10,10,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,83,83,44,38,16,13,16,16,16,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,63,45,34,23,17,12,9,8,8,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,77,66,61,61,61,55,2,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,81,54,44,39,38,33,29,29,32,27,...,25,26,31,32,37,42,42,45,50,NaN
10,82,70,51,39,26,19,15,9,7,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,71,51,28,18,13,13,11,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,70,61,53,46,40,33,31,26,22,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,84,78,76,74,70,68,74,75,69,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,59,53,38,28,21,18,16,14,12,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,60,37,29,24,22,21,18,16,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,82,68,50,50,41,37,26,22,22,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,81,68,62,51,42,35,28,28,28,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,72,57,52,47,42,31,24,18,17,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,99,92,81,59,47,42,32,27,18,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,63,55,48,39,35,24,3,2,2,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,77,54,50,43,30,27,21,18,15,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,51,39,34,26,26,19,2,2,3,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,74,71,65,62,57,50,40,37,22,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,81,70,68,67,66,57,54,53,51,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,74,63,35,26,26,23,20,16,13,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,50,39,30,28,21,19,20,17,17,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,81,68,44,16,11,9,8,7,8,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,94,86,69,50,41,33,32,28,28,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,92,80,72,69,67,61,54,43,38,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,91,87,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,98,96,93,93,93,92,92,92,90,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,89,88,88,91,95,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,91,91,90,95,95,99,96,96,92,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,95,88,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,97,97,89,89,94,90,99,97,98,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,98,98,92,89,92,93,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,96,89,92,96,96,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,99,100,98,99,99,99,98,90,99,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,98,100,100,90,93,94,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,92,92,95,91,91,94,100,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,92,91,98,100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,92,92,97,100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,100,99,99,NaN,NaN,98,94,92,95,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,92,NaN,NaN,95,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,97,93,96,100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,100,99,97,97,100,95,99,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,97,97,96,95,100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,96,95,99,99,100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,96,96,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,100,97,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,98,98,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,98,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,99,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,99,99,99,99,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,99,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,99,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [683]:
#bb.iloc[:,8:] = bb.iloc[:,8:].apply(pd.to_numeric, errors = 'ignore')
bb.dtypes

year                     int64
artist                  object
track                   object
time                    object
Total_Sec                int64
genre                   object
date_entered    datetime64[ns]
date_peaked     datetime64[ns]
x1st_week                int64
x2nd_week               object
x3rd_week               object
x4th_week               object
x5th_week               object
x6th_week               object
x7th_week               object
x8th_week               object
x9th_week               object
x10th_week              object
x11th_week              object
x12th_week              object
x13th_week              object
x14th_week              object
x15th_week              object
x16th_week              object
x17th_week              object
x18th_week              object
x19th_week              object
x20th_week              object
x21st_week              object
x22nd_week              object
                     ...
x36th_week              object
x37th_week              object
x38th_week              object
x39th_week              object
x40th_week              object
x41st_week              object
x42nd_week              object
x43rd_week              object
x44th_week              object
x45th_week              object
x46th_week              object
x47th_week              object
x48th_week              object
x49th_week              object
x50th_week              object
x51st_week              object
x52nd_week              object
x53rd_week              object
x54th_week              object
x55th_week              object
x56th_week              object
x57th_week              object
x58th_week              object
x59th_week              object
x60th_week              object
x61st_week              object
x62nd_week              object
x63rd_week              object
x64th_week              object
x65th_week              object
dtype: object

### Creating a column called count_weeks which is the total amount of weeks on the billboard top 100

In [684]:
count_weeks = bb.loc[:,[x for x in bb.columns if 'week' in x]].count(axis = 1)

In [685]:
bb.insert(8,'chart_weeks',count_weeks)

In [686]:
bb.head()

,year,artist,track,time,Total_Sec,genre,date_entered,date_peaked,chart_weeks,x1st_week,...,x56th_week,x57th_week,x58th_week,x59th_week,x60th_week,x61st_week,x62nd_week,x63rd_week,x64th_week,x65th_week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",218,Rock,2000-09-23,2000-11-18,28,78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria","4,18,00 AM",258,Rock,2000-02-12,2000-04-08,26,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,"4,07,00 AM",247,Rock,1999-10-23,2000-01-29,33,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,"3,45,00 AM",225,Rock,2000-08-12,2000-09-16,24,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",218,Rock,2000-08-05,2000-10-14,21,57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [385]:
bb['genre'].unique()

array(['Rock', "Rock'n'roll", 'Latin', 'Country', 'Rap', 'Pop',
       'Electronica', 'Jazz', 'R&B', 'Reggae', 'Gospel', 'R & B'], dtype=object)

In [443]:
criteria = bb['genre'] == 'Rock'
bb[criteria].loc[:,'artist'].value_counts()

Braxton, Toni          3
Thomas, Carl           3
Jagged Edge            2
Nine Days              2
Savage Garden          2
3 Doors Down           2
Carey, Mariah          2
Third Eye Blind        2
Ginuwine               2
Henley, Don            1
TLC                    1
Wallflowers, The       1
Tuesday                1
Carter, Torrey         1
Jones, Donell          1
Bega, Lou              1
Kandi                  1
Janet                  1
Moore, Chante          1
Kid Rock               1
Estefan, Gloria        1
Changing Faces         1
Blink-182              1
Williams, Robbie       1
Badu, Erkyah           1
Westlife               1
Tamia                  1
Papa Roach             1
Sister Hazel           1
Pearl Jam              1
                      ..
Train                  1
Dion, Celine           1
Barenaked Ladies       1
Goo Goo Dolls          1
Sammie                 1
Usher                  1
matchbox twenty        1
Spencer, Tracie        1
Sting                  1
Tamar                  1
R.E.M.                 1
Kravitz, Lenny         1
Amber                  1
En Vogue               1
Dream                  1
Counting Crows         1
Bon Jovi               1
Filter                 1
Foo Fighters           1
Stone Temple Pilots    1
BBMak                  1
Mary Mary              1
Hollister, Dave        1
McKnight, Brian        1
Before Dark            1
Sugar Ray              1
Zombie Nation          1
Offspring, The         1
No Doubt               1
Santana                1
Name: artist, dtype: int64

## Cleaning the Genre Field

#### There are 24 artists that are associated with more than 1 unique genres. Thus we need to resolve this. For instance, Christina Aguilera would be considered Pop genre, but is tied to Rock and Rock n' Roll. To get proper genres, need to go through each artist and find out what their main genre would be.

In [437]:
bb_genre = bb.groupby('artist')['genre'].nunique().to_frame()
print bb_genre[bb_genre['genre'] > 1].count()
bb_genre_fix = bb_genre[bb_genre['genre'] > 1]
bb_genre_fix

genre    0
dtype: int64

Empty DataFrame
Columns: [genre]
Index: []

In [388]:
artist = []
for x in bb_genre_fix.index:
    artist.append(x)
bb_genre_artist_fix = bb[bb['artist'].isin(artist)]
bb_genre_artist_fix

,year,artist,track,time,Total_Sec,genre,date_entered,date_peaked,x1st_week,x2nd_week,...,x56th_week,x57th_week,x58th_week,x59th_week,x60th_week,x61st_week,x62nd_week,x63rd_week,x64th_week,x65th_week
0,2000,Destiny's Child,Independent Women Part I,"3,38,00 AM",218,Rock,2000-09-23,2000-11-18,78,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),"3,38,00 AM",218,Rock,2000-08-05,2000-10-14,57,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2000,Destiny's Child,Say My Name,"4,31,00 AM",271,Rock'n'roll,1999-12-25,2000-03-18,83,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2000,Sisqo,Incomplete,"3,52,00 AM",232,Rock'n'roll,2000-06-24,2000-08-12,77,66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2000,N'Sync,It's Gonna Be Me,"3,10,00 AM",190,Rock'n'roll,2000-05-06,2000-07-29,82,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2000,"Aguilera, Christina",What A Girl Wants,"3,18,00 AM",198,Rock'n'roll,1999-11-27,2000-01-15,71,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2000,Vertical Horizon,Everything You Want,"4,01,00 AM",241,Rock'n'roll,2000-01-22,2000-07-15,70,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2000,Aaliyah,Try Again,"4,03,00 AM",243,Rock'n'roll,2000-03-18,2000-06-17,59,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2000,Mya,Case Of The Ex (Whatcha Gonna Do),"3,50,00 AM",230,Rock'n'roll,2000-08-19,2000-12-02,72,57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2000,Destiny's Child,Jumpin' Jumpin',"3,48,00 AM",228,Rock,2000-05-13,2000-08-19,74,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2000,Sisqo,Thong Song,"4,05,00 AM",245,Rock'n'roll,2000-01-29,2000-05-20,74,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2000,"Aguilera, Christina",I Turn To You,"4,00,00 AM",240,Rock'n'roll,2000-04-15,2000-07-01,50,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2000,"Houston, Whitney",My Love Is Your Love,"4,16,00 AM",256,Rock'n'roll,1999-09-04,2000-01-08,81,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2000,Joe,I Wanna Know,"4,57,00 AM",297,Rock'n'roll,2000-01-01,2000-07-01,94,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2000,N'Sync,Bye Bye Bye,"3,15,00 AM",195,Rock'n'roll,2000-01-29,2000-04-15,42,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2000,Pink,Most Girls,"4,06,00 AM",246,Rock'n'roll,2000-08-12,2000-11-25,85,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2000,N'Sync,This I Promise You,"4,23,00 AM",263,Rock,2000-09-30,2000-12-02,68,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2000,"Backstreet Boys, The",Show Me The Meaning Of Being Lonely,"3,54,00 AM",234,Rock,2000-01-01,2000-03-18,74,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2000,Nine Days,Absolutely (Story Of A Girl),"3,09,00 AM",189,Rock,2000-05-06,2000-07-22,85,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2000,Pink,There U Go,"3,23,00 AM",203,Rock,2000-03-04,2000-04-08,25,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,2000,"Spears, Britney",Oops!.. I Did It Again,"3,30,00 AM",210,Rock'n'roll,2000-04-22,2000-06-10,67,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,2000,"Backstreet Boys, The",Shape Of My Heart,"3,49,00 AM",229,Rock'n'roll,2000-10-14,2000-12-02,39,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2000,"Spears, Britney",From The Bottom Of My Broken Heart,"4,30,00 AM",270,Rock,2000-01-29,2000-02-26,76,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,2000,Third Eye Blind,Never Let You Go,"3,57,00 AM",237,Rock,2000-01-22,2000-04-01,65,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,2000,Red Hot Chili Peppers,Otherside,"4,13,00 AM",253,Rock,2000-02-12,2000-05-27,80,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,2000,"Simpson, Jessica",I Think I'm In Love With You,"3,32,00 AM",212,Pop,2000-07-01,2000-08-12,63,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2000,Vertical Horizon,You're A God,"3,45,00 AM",225,Rock,2000-08-26,2000-11-04,64,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2000,Avant,Separated,"4,13,00 AM",253,Rock,2000-04-29,2000-05-20,62,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,2000,"Spears, Britney",Lucky,"3,23,00 AM",203,Rock,2000-08-12,2000-09-09,61,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,2000,D'Angelo,Untitled (How Does It Feel),"7,10,00 AM",430,R&B,2000-01-22,2000-02-19,77,56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2000,Avant,My First Love,"4,28,00 AM",268,Rock'n'roll,2000-11-04,2000-12-16,70,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,2000,"Houston, Whitney",I Learned From The Best,"4,18,00 AM",258,Rock,2000-02-19,2000-03-25,83,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,2000,"Backstreet Boys, The",The One,"3,46,00 AM",226,Rock,2000-05-27,2000-07-01,58,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,2000,Aaliyah,I Don't Wanna,"4,15,00 AM",255,Rock,2000-01-29,2000-03-04,84,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,2000,Vitamin C,Graduation (Friends Forever),"4,23,00 AM",263,Rock,2000-04-15,2000-06-10,81,64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,2000,Sisqo,Got To Get It,"3,52,00 AM",232,Rock,1999-11-20,2000-01-22,92,76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,2000,Vitamin C,The Itch,"3,30,00 AM",210,Rock'n'roll,2000-12-02,2000-12-16,86,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,2000,Mya,The Best Of Me,"4,12,00 AM",252,Rock,2000-04-15,2000-05-20,85,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,2000,"Houston, Whitney",Could I Have This Kiss Forever,"3,54,00 AM",234,Rock,2000-06-17,2000-08-05,74,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,2000,LFO,I Don't Wanna Kiss You Goodnight,"5,00,00 AM",300,Rock,2000-04-15,2000-04-22,63,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,2000,"Simpson, Jessica",Where You Are,"3,51,00 AM",231,Rock,2000-04-01,2000-04-15,73,66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,2000,Joe,Treat Her Like A Lady,"4,12,00 AM",252,Rock,2000-08-05,2000-08-19,77,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,2000,"Blige, Mary J.",Deep Inside,"5,26,00 AM",326,Rock,1999-11-13,2000-01-22,83,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,2000,"Price, Kelly",You Should've Told Me,"3,12,00 AM",192,Rock,2000-09-23,2000-12-02,91,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,2000,Limp Bizkit,Rollin',"4,04,00 AM",244,Rock'n'roll,2000-11-11,2000-12-09,77,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,2000,"Price, Kelly",As We Lay,"6,20,00 AM",380,Rock'n'roll,2000-07-15,2000-08-05,82,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,2000,Nine Days,If I Am,"4,18,00 AM",258,Rock'n'roll,2000-12-02,2000-12-02,68,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,2000,"Blige, Mary J.",Give Me You,"5,00,00 AM",300,Rock'n'roll,2000-04-15,2000-05-13,97,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,2000,Red Hot Chili Peppers,Californication,"5,21,00 AM",321,Rock'n'roll,2000-07-29,2000-10-14,72,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,2000,Third Eye Blind,Deep Inside Of You,"4,10,00 AM",250,Rock'n'roll,2000-09-02,2000-10-07,80,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,2000,"Houston, Whitney","Same Script, Different Cast","4,45,00 AM",285,Rock,2000-06-17,2000-07-15,71,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,2000,D'Angelo,Left & Right,"4,35,00 AM",275,R & B,1999-12-11,2000-01-01,93,77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,2000,Limp Bizkit,N 2 Gether Now,"3,55,00 AM",235,Rock,1999-12-04,2000-01-08,94,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,2000,Metallica,No Leaf Clover (Live),"5,43,00 AM",343,Rock,2000-02-12,2000-03-11,86,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,2000,Metallica,I Disappear,"4,26,00 AM",266,Rock'n'roll,2000-05-13,2000-06-17,86,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,2000,LFO,West Side Story,"3,27,00 AM",207,Rock'n'roll,2000-08-05,2000-08-12,96,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,2000,Limp Bizkit,Re-Arranged,"4,08,00 AM",248,Rock,1999-12-04,2000-02-05,91,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,2000,"Price, Kelly",Love Sets You Free,"3,46,00 AM",226,Rock,2000-05-13,2000-05-20,92,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [522]:
#replace 'R & B' to 'R&B'
bb['genre'].replace('R & B','R&B',inplace = True)
bb['genre'].unique()

array(['R&B', 'Rock', 'Pop', 'Latin', 'Country', 'Rap', 'Electronica',
       'Jazz', 'Reggae', 'Gospel'], dtype=object)

In [523]:
#replace "Rock'n'roll" to 'Rock'
bb['genre'].replace('Rock\'n\'roll','Rock',inplace = True)
bb['genre'].unique()

array(['R&B', 'Rock', 'Pop', 'Latin', 'Country', 'Rap', 'Electronica',
       'Jazz', 'Reggae', 'Gospel'], dtype=object)

In [423]:
artist_list = []
for x in bb.artist:
    artist_list.append(x)
    
print sorted(artist_list)

['2 Pac', '2Ge+her', '3 Doors Down', '3 Doors Down', '504 Boyz', '98\xa1', 'A*Teens', 'Aaliyah', 'Aaliyah', 'Adams, Yolanda', 'Adkins, Trace', 'Aguilera, Christina', 'Aguilera, Christina', 'Aguilera, Christina', 'Alice Deejay', 'Allan, Gary', 'Amber', 'Anastacia', 'Anthony, Marc', 'Anthony, Marc', 'Avant', 'Avant', 'BBMak', 'Backstreet Boys, The', 'Backstreet Boys, The', 'Backstreet Boys, The', 'Badu, Erkyah', 'Baha Men', 'Barenaked Ladies', 'Beenie Man', 'Before Dark', 'Bega, Lou', 'Big Punisher', 'Black Rob', 'Black, Clint', 'Blaque', 'Blige, Mary J.', 'Blige, Mary J.', 'Blink-182', 'Bloodhound Gang', 'Bon Jovi', 'Braxton, Toni', 'Braxton, Toni', 'Braxton, Toni', 'Brock, Chad', 'Brock, Chad', 'Brooks & Dunn', 'Brooks, Garth', 'Byrd, Tracy', 'Cagle, Chris', "Cam'ron", 'Carey, Mariah', 'Carey, Mariah', 'Carter, Aaron', 'Carter, Torrey', 'Changing Faces', 'Chesney, Kenny', 'Chesney, Kenny', 'Clark Family Experience', 'Clark, Terri', 'Common', 'Counting Crows', 'Creed', 'Creed', 'Cyrus, Billy Ray', "D'Angelo", "D'Angelo", 'DMX', 'DMX', 'DMX', 'Da Brat', 'Da Brat', 'Davidson, Clay', 'De La Soul', "Destiny's Child", "Destiny's Child", "Destiny's Child", 'Diffie, Joe', 'Diffie, Joe', 'Dion, Celine', 'Dixie Chicks, The', 'Dixie Chicks, The', 'Dixie Chicks, The', 'Dixie Chicks, The', 'Dr. Dre', 'Dr. Dre', 'Drama', 'Dream', 'Eastsidaz, The', 'Eastsidaz, The', 'Eiffel 65', 'Elliott, Missy "Misdemeanor"', 'Eminem', 'Eminem', 'Eminem', 'En Vogue', 'Estefan, Gloria', 'Evans, Sara', 'Eve', 'Eve', 'Everclear', 'Fabian, Lara', 'Fatboy Slim', 'Filter', 'Foo Fighters', 'Fragma', 'Funkmaster Flex', 'Ghostface Killah', 'Gill, Vince', 'Gilman, Billy', 'Ginuwine', 'Ginuwine', 'Goo Goo Dolls', 'Gray, Macy', 'Griggs, Andy', 'Guy', 'Hanson', 'Hart, Beth', 'Heatherly, Eric', 'Henley, Don', 'Herndon, Ty', 'Hill, Faith', 'Hill, Faith', 'Hoku', 'Hollister, Dave', 'Hot Boys', 'Houston, Whitney', 'Houston, Whitney', 'Houston, Whitney', 'Houston, Whitney', 'IMx', 'Ice Cube', 'Ideal', 'Iglesias, Enrique', 'Iglesias, Enrique', 'J-Shin', 'Ja Rule', 'Jackson, Alan', 'Jackson, Alan', 'Jackson, Alan', 'Jagged Edge', 'Jagged Edge', 'Janet', 'Jay-Z', 'Jay-Z', 'Jay-Z', 'Jay-Z', 'Jay-Z', 'Jean, Wyclef', 'Joe', 'Joe', 'John, Elton', 'Jones, Donell', 'Jordan, Montell', 'Juvenile', 'Kandi', 'Keith, Toby', 'Keith, Toby', 'Kelis', 'Kenny G', 'Kid Rock', 'Kravitz, Lenny', 'Kumbia Kings', 'LFO', 'LFO', 'LL Cool J', 'Larrieux, Amel', 'Lawrence, Tracy', 'Levert, Gerald', 'Levert, Gerald', 'Lil Bow Wow', 'Lil Wayne', "Lil' Kim", "Lil' Kim", "Lil' Mo", "Lil' Zane", 'Limp Bizkit', 'Limp Bizkit', 'Limp Bizkit', 'Lonestar', 'Lonestar', 'Lonestar', 'Lopez, Jennifer', 'Loveless, Patty', 'Lox', 'Lucy Pearl', 'Ludacris', 'M2M', 'M2M', 'Madison Avenue', 'Madonna', 'Madonna', 'Martin, Ricky', 'Martin, Ricky', 'Martin, Ricky', 'Mary Mary', 'Master P', 'McBride, Martina', 'McBride, Martina', 'McEntire, Reba', 'McEntire, Reba', 'McGraw, Tim', 'McGraw, Tim', 'McGraw, Tim', 'McKnight, Brian', 'Messina, Jo Dee', 'Messina, Jo Dee', 'Metallica', 'Metallica', 'Montgomery Gentry', 'Montgomery, John Michael', 'Moore, Chante', 'Moore, Mandy', 'Mumba, Samantha', 'Musiq', 'Mya', 'Mya', 'Mystikal', "N'Sync", "N'Sync", "N'Sync", 'Nas', 'Nelly', 'Next', 'Nine Days', 'Nine Days', 'No Doubt', 'Nu Flavor', 'Offspring, The', 'Paisley, Brad', 'Paisley, Brad', 'Papa Roach', 'Pearl Jam', 'Pink', 'Pink', 'Price, Kelly', 'Price, Kelly', 'Price, Kelly', 'Profyle', 'Puff Daddy', 'Q-Tip', 'R.E.M.', 'Rascal Flatts', 'Raye, Collin', 'Red Hot Chili Peppers', 'Red Hot Chili Peppers', 'Rimes, LeAnn', 'Rimes, LeAnn', 'Rimes, LeAnn', 'Rogers, Kenny', 'Ruff Endz', 'Sammie', 'Santana', 'Savage Garden', 'Savage Garden', 'SheDaisy', 'SheDaisy', 'SheDaisy', 'Sheist, Shade', 'Shyne', 'Simpson, Jessica', 'Simpson, Jessica', 'Sisqo', 'Sisqo', 'Sisqo', 'Sister Hazel', 'Smash Mouth', 'Smith, Will', 'Son By Four', 'Sonique', 'SoulDecision', 'Spears, Britney', 'Spears, Britney', 'Spears, Britney', 'Spencer, Tracie', 'Splender', 'Sting', 'Stone Temple Pilots', 'Stone, Angie', 'Strait, George', 'Strait, George', 'Sugar Ray', 'TLC', 'Tamar', 'Tamia', 'Third Eye Blind', 'Third Eye Blind', 'Thomas, Carl', 'Thomas, Carl', 'Thomas, Carl', 'Tippin, Aaron', 'Train', 'Trick Daddy', 'Trina', 'Tritt, Travis', 'Tuesday', 'Urban, Keith', 'Usher', 'Vassar, Phil', 'Vassar, Phil', 'Vertical Horizon', 'Vertical Horizon', 'Vitamin C', 'Vitamin C', 'Walker, Clay', 'Walker, Clay', 'Wallflowers, The', 'Westlife', 'Williams, Robbie', 'Wills, Mark', 'Worley, Darryl', 'Wright, Chely', 'Yankee Grey', 'Yearwood, Trisha', 'Ying Yang Twins', 'Zombie Nation', 'matchbox twenty']

In [405]:
#setting 98 deg to Pop
bb.iloc[22,5] = 'Pop'

In [519]:
#setting all artists that have multiple genres to one genre
bb.loc[bb['artist']=='Madonna','genre'] = 'Pop'
bb.loc[bb['artist']=='Aaliyah','genre'] = 'R&B'
bb.loc[bb['artist']=='Aguilera, Christina','genre'] = 'Pop'
bb.loc[bb['artist']=='Avant','genre'] = 'R&B'
bb.loc[bb['artist']=='Backstreet Boys, The','genre'] = 'Pop'

bb.loc[bb['artist']=='Blige, Mary J.','genre'] = 'R&B'
bb.loc[bb['artist']=='Houston, Whitney','genre'] = 'R&B'
bb.loc[bb['artist']=='Joe','genre'] = 'R&B'

bb.loc[bb['artist']=='Price, Kelly','genre'] = 'R&B'
bb.loc[bb['artist']=='Mya','genre'] = 'R&B'
bb.loc[bb['artist']=='Sisqo','genre'] = 'R&B'
bb.loc[bb['artist']=='LFO','genre'] = 'Electronica'
bb.loc[bb['artist']=='Limp Bizkit','genre'] = 'Rock'
bb.loc[bb['artist']=='Metallica','genre'] = 'Rock'
bb.loc[bb['artist']=='Red Hot Chili Peppers','genre'] = 'Rock'
bb.loc[bb['artist']=='Price, Kelly','genre'] = 'R&B'
bb.loc[bb['artist']=='Destiny\'s Child','genre'] = 'R&B'
bb.loc[bb['artist']=='Avant','genre'] = 'R&B'
bb.loc[bb['artist']=='N\'Sync','genre'] = 'Pop'
bb.loc[bb['artist']=='Pink','genre'] = 'Pop'
bb.loc[bb['artist']=='Simpson, Jessica','genre'] = 'Pop'
bb.loc[bb['artist']=='Spears, Britney','genre'] = 'Pop'
bb.loc[bb['artist']=='Vertical Horizon','genre'] = 'Pop'
bb.loc[bb['artist']=='Vitamin C','genre'] = 'Pop'
bb.loc[bb['artist']=='Nine Days','genre'] = 'Rock'
bb.loc[bb['artist']=='Third Eye Blind','genre'] = 'Rock'

In [457]:
artist_set = set(artist_list)

In [464]:
artist_set

{'2 Pac',
 '2Ge+her',
 '3 Doors Down',
 '504 Boyz',
 '98\xa1',
 'A*Teens',
 'Aaliyah',
 'Adams, Yolanda',
 'Adkins, Trace',
 'Aguilera, Christina',
 'Alice Deejay',
 'Allan, Gary',
 'Amber',
 'Anastacia',
 'Anthony, Marc',
 'Avant',
 'BBMak',
 'Backstreet Boys, The',
 'Badu, Erkyah',
 'Baha Men',
 'Barenaked Ladies',
 'Beenie Man',
 'Before Dark',
 'Bega, Lou',
 'Big Punisher',
 'Black Rob',
 'Black, Clint',
 'Blaque',
 'Blige, Mary J.',
 'Blink-182',
 'Bloodhound Gang',
 'Bon Jovi',
 'Braxton, Toni',
 'Brock, Chad',
 'Brooks & Dunn',
 'Brooks, Garth',
 'Byrd, Tracy',
 'Cagle, Chris',
 "Cam'ron",
 'Carey, Mariah',
 'Carter, Aaron',
 'Carter, Torrey',
 'Changing Faces',
 'Chesney, Kenny',
 'Clark Family Experience',
 'Clark, Terri',
 'Common',
 'Counting Crows',
 'Creed',
 'Cyrus, Billy Ray',
 "D'Angelo",
 'DMX',
 'Da Brat',
 'Davidson, Clay',
 'De La Soul',
 "Destiny's Child",
 'Diffie, Joe',
 'Dion, Celine',
 'Dixie Chicks, The',
 'Dr. Dre',
 'Drama',
 'Dream',
 'Eastsidaz, The',
 'Eiffel 65',
 'Elliott, Missy "Misdemeanor"',
 'Eminem',
 'En Vogue',
 'Estefan, Gloria',
 'Evans, Sara',
 'Eve',
 'Everclear',
 'Fabian, Lara',
 'Fatboy Slim',
 'Filter',
 'Foo Fighters',
 'Fragma',
 'Funkmaster Flex',
 'Ghostface Killah',
 'Gill, Vince',
 'Gilman, Billy',
 'Ginuwine',
 'Goo Goo Dolls',
 'Gray, Macy',
 'Griggs, Andy',
 'Guy',
 'Hanson',
 'Hart, Beth',
 'Heatherly, Eric',
 'Henley, Don',
 'Herndon, Ty',
 'Hill, Faith',
 'Hoku',
 'Hollister, Dave',
 'Hot Boys',
 'Houston, Whitney',
 'IMx',
 'Ice Cube',
 'Ideal',
 'Iglesias, Enrique',
 'J-Shin',
 'Ja Rule',
 'Jackson, Alan',
 'Jagged Edge',
 'Janet',
 'Jay-Z',
 'Jean, Wyclef',
 'Joe',
 'John, Elton',
 'Jones, Donell',
 'Jordan, Montell',
 'Juvenile',
 'Kandi',
 'Keith, Toby',
 'Kelis',
 'Kenny G',
 'Kid Rock',
 'Kravitz, Lenny',
 'Kumbia Kings',
 'LFO',
 'LL Cool J',
 'Larrieux, Amel',
 'Lawrence, Tracy',
 'Levert, Gerald',
 'Lil Bow Wow',
 'Lil Wayne',
 "Lil' Kim",
 "Lil' Mo",
 "Lil' Zane",
 'Limp Bizkit',
 'Lonestar',
 'Lopez, Jennifer',
 'Loveless, Patty',
 'Lox',
 'Lucy Pearl',
 'Ludacris',
 'M2M',
 'Madison Avenue',
 'Madonna',
 'Martin, Ricky',
 'Mary Mary',
 'Master P',
 'McBride, Martina',
 'McEntire, Reba',
 'McGraw, Tim',
 'McKnight, Brian',
 'Messina, Jo Dee',
 'Metallica',
 'Montgomery Gentry',
 'Montgomery, John Michael',
 'Moore, Chante',
 'Moore, Mandy',
 'Mumba, Samantha',
 'Musiq',
 'Mya',
 'Mystikal',
 "N'Sync",
 'Nas',
 'Nelly',
 'Next',
 'Nine Days',
 'No Doubt',
 'Nu Flavor',
 'Offspring, The',
 'Paisley, Brad',
 'Papa Roach',
 'Pearl Jam',
 'Pink',
 'Price, Kelly',
 'Profyle',
 'Puff Daddy',
 'Q-Tip',
 'R.E.M.',
 'Rascal Flatts',
 'Raye, Collin',
 'Red Hot Chili Peppers',
 'Rimes, LeAnn',
 'Rogers, Kenny',
 'Ruff Endz',
 'Sammie',
 'Santana',
 'Savage Garden',
 'SheDaisy',
 'Sheist, Shade',
 'Shyne',
 'Simpson, Jessica',
 'Sisqo',
 'Sister Hazel',
 'Smash Mouth',
 'Smith, Will',
 'Son By Four',
 'Sonique',
 'SoulDecision',
 'Spears, Britney',
 'Spencer, Tracie',
 'Splender',
 'Sting',
 'Stone Temple Pilots',
 'Stone, Angie',
 'Strait, George',
 'Sugar Ray',
 'TLC',
 'Tamar',
 'Tamia',
 'Third Eye Blind',
 'Thomas, Carl',
 'Tippin, Aaron',
 'Train',
 'Trick Daddy',
 'Trina',
 'Tritt, Travis',
 'Tuesday',
 'Urban, Keith',
 'Usher',
 'Vassar, Phil',
 'Vertical Horizon',
 'Vitamin C',
 'Walker, Clay',
 'Wallflowers, The',
 'Westlife',
 'Williams, Robbie',
 'Wills, Mark',
 'Worley, Darryl',
 'Wright, Chely',
 'Yankee Grey',
 'Yearwood, Trisha',
 'Ying Yang Twins',
 'Zombie Nation',
 'matchbox twenty'}